var CANVAS_WIDTH = 1600;
var CANVAS_HEIGHT = 768;

var DISABLE_SOUND_MOBILE = false;

var EDGEBOARD_X = 270;
var EDGEBOARD_Y = 60;

var FPS_TIME      = 1000/30;
var FONT_GAME = "arialbold";

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP   = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT  = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END   = 5;
var ON_PRESS_MOVE = 6;

var NUM_LANGUAGES = 6;
var TIME_LEVEL;
var MAX_CHAR_VALUE;
var CELL_WIDTH = 86;
var CELL_HEIGHT = 86;
var MAX_WORD_LENGTH = 8;
var MAX_WORDS_WRITTEN_VIEWABLE = 22;
var SCORE_WORD_WRONG;
var NUM_ROWS = 7;
var NUM_COLS = 7;

var LABEL_LANG_0 = 0;
var LABEL_LANG_1 = 1;
var LABEL_LANG_2 = 2;
var LABEL_LANG_3 = 3;
var LABEL_LANG_4 = 4;
var LABEL_LANG_5 = 5;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;
var SOUNDTRACK_VOLUME_IN_GAME  = 1;